-- =============================================================================
-- MIGRASI DATABASE: MODE PIONIR
-- Sistem Penilaian Pegawai & Papan Juri (Babel Memilih)
-- Tanggal: 2026-09-20
-- =============================================================================

-- 1. Tambahkan nilai 'MODE_PIONIR' ke enum mode_penilaian_enum jika belum ada
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type typ
    JOIN pg_enum enm ON typ.oid = enm.enumtypid
    WHERE typ.typname = 'mode_penilaian_enum' AND enm.enumlabel = 'MODE_PIONIR'
  ) THEN
    ALTER TYPE public.mode_penilaian_enum ADD VALUE 'MODE_PIONIR';
  END IF;
END $$;

-- 2. Tambah kolom tgl_selesai_fase1 di periode_penilaian
ALTER TABLE public.periode_penilaian
ADD COLUMN IF NOT EXISTS tgl_selesai_fase1 TIMESTAMP WITH TIME ZONE;

-- 3. Tambah kolom bobot di tabel pertanyaan (default 0.20 untuk 5 pilar kriteria)
ALTER TABLE public.pertanyaan
ADD COLUMN IF NOT EXISTS bobot NUMERIC DEFAULT 0.20;

-- 4. Tambah kolom nilai_ckp di tabel nominee_periode
ALTER TABLE public.nominee_periode
ADD COLUMN IF NOT EXISTS nilai_ckp NUMERIC DEFAULT 0;

-- 5. Tabel Pengusul Periode (Designated Nominators)
CREATE TABLE IF NOT EXISTS public.pengusul_periode (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode_id BIGINT NOT NULL REFERENCES public.periode_penilaian(id) ON DELETE CASCADE,
  pegawai_id BIGINT NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  token_akses UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  is_digunakan BOOLEAN DEFAULT FALSE,
  submitted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT uq_pengusul_periode UNIQUE (periode_id, pegawai_id)
);

CREATE INDEX IF NOT EXISTS idx_pengusul_token ON public.pengusul_periode(token_akses);
CREATE INDEX IF NOT EXISTS idx_pengusul_periode_id ON public.pengusul_periode(periode_id);

-- 6. Tabel Penilaian Pengusul (Fase 1)
CREATE TABLE IF NOT EXISTS public.penilaian_pionir_pengusul (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode_id BIGINT NOT NULL REFERENCES public.periode_penilaian(id) ON DELETE CASCADE,
  pengusul_id BIGINT NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  kandidat_id BIGINT NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  pertanyaan_id BIGINT NOT NULL REFERENCES public.pertanyaan(id) ON DELETE CASCADE,
  skor NUMERIC NOT NULL,
  kata_kunci TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT uq_penilaian_pionir_item UNIQUE (periode_id, pengusul_id, kandidat_id, pertanyaan_id),
  CONSTRAINT chk_anti_self_pionir CHECK (pengusul_id <> kandidat_id)
);

CREATE INDEX IF NOT EXISTS idx_penilaian_pionir_periode ON public.penilaian_pionir_pengusul(periode_id);
CREATE INDEX IF NOT EXISTS idx_penilaian_pionir_kandidat ON public.penilaian_pionir_pengusul(kandidat_id);

-- 7. Tabel Suara Pemilih Umum (Fase 2 - Mode Rahasia LUBER)
CREATE TABLE IF NOT EXISTS public.suara_pionir (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode_id BIGINT NOT NULL REFERENCES public.periode_penilaian(id) ON DELETE CASCADE,
  kandidat_id BIGINT NOT NULL REFERENCES public.pegawai(id) ON DELETE CASCADE,
  voter_hash TEXT, -- Identifier anonim untuk audit trail tanpa mengekspos identitas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_suara_pionir_periode ON public.suara_pionir(periode_id);
CREATE INDEX IF NOT EXISTS idx_suara_pionir_kandidat ON public.suara_pionir(kandidat_id);

-- 8. Kebijakan Row Level Security (RLS) & Izin Tabel (Grants)
ALTER TABLE public.pengusul_periode ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penilaian_pionir_pengusul ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suara_pionir ENABLE ROW LEVEL SECURITY;

-- Pengusul Periode: Izinkan akses penuh untuk Admin & Tim Pengusul
DROP POLICY IF EXISTS "Allow all pengusul_periode" ON public.pengusul_periode;
CREATE POLICY "Allow all pengusul_periode" ON public.pengusul_periode
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Penilaian Pengusul: Izinkan insert & select instrumen
DROP POLICY IF EXISTS "Allow all penilaian_pionir_pengusul" ON public.penilaian_pionir_pengusul;
CREATE POLICY "Allow all penilaian_pionir_pengusul" ON public.penilaian_pionir_pengusul
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Suara Pemilih Umum: Izinkan voting rahasia LUBER & audit trail
DROP POLICY IF EXISTS "Allow all suara_pionir" ON public.suara_pionir;
CREATE POLICY "Allow all suara_pionir" ON public.suara_pionir
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

GRANT ALL ON TABLE public.pengusul_periode TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.penilaian_pionir_pengusul TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.suara_pionir TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 9. View Tabulasi Mode PIONIR
CREATE OR REPLACE VIEW public.view_tabulasi_mode_pionir WITH (security_invoker=off) AS
WITH 
suara_pengusul_cte AS (
  SELECT 
    periode_id,
    kandidat_id,
    COUNT(DISTINCT pengusul_id) AS suara_pengusul
  FROM public.penilaian_pionir_pengusul
  GROUP BY periode_id, kandidat_id
),
suara_pemilih_cte AS (
  SELECT 
    periode_id,
    kandidat_id,
    COUNT(*) AS suara_pemilih
  FROM public.suara_pionir
  GROUP BY periode_id, kandidat_id
),
skor_kuesioner_per_pengusul AS (
  SELECT 
    ppp.periode_id,
    ppp.pengusul_id,
    ppp.kandidat_id,
    SUM(ppp.skor * COALESCE(p.bobot, 0.20)) AS skor_tertimbang_pengusul
  FROM public.penilaian_pionir_pengusul ppp
  JOIN public.pertanyaan p ON p.id = ppp.pertanyaan_id
  GROUP BY ppp.periode_id, ppp.pengusul_id, ppp.kandidat_id
),
rerata_kuesioner_cte AS (
  SELECT 
    periode_id,
    kandidat_id,
    ROUND(AVG(skor_tertimbang_pengusul), 2) AS rata_skor_kuesioner
  FROM skor_kuesioner_per_pengusul
  GROUP BY periode_id, kandidat_id
),
kata_kunci_cte AS (
  SELECT 
    periode_id,
    kandidat_id,
    STRING_AGG(DISTINCT TRIM(kata_kunci), ', ') FILTER (WHERE kata_kunci IS NOT NULL AND TRIM(kata_kunci) != '') AS kumpulan_kata
  FROM public.penilaian_pionir_pengusul
  GROUP BY periode_id, kandidat_id
),
total_suara_periode_cte AS (
  SELECT 
    pp.id AS periode_id,
    (
      COALESCE((SELECT COUNT(DISTINCT ppp2.pengusul_id) FROM public.penilaian_pionir_pengusul ppp2 WHERE ppp2.periode_id = pp.id), 0) +
      COALESCE((SELECT COUNT(*) FROM public.suara_pionir sp2 WHERE sp2.periode_id = pp.id), 0)
    ) AS total_suara_masuk
  FROM public.periode_penilaian pp
),
kandidat_gabungan AS (
  SELECT 
    np.periode_id,
    np.id AS nominee_periode_id,
    np.pegawai_id AS nominee_id,
    p.nama AS nama_nominee,
    p.nip,
    p.nip_baru,
    p.jabatan,
    w.nama_wilayah AS unit_kerja,
    p.foto_url,
    COALESCE(np.nilai_ckp, 0) AS nilai_ckp,
    COALESCE(sp.suara_pengusul, 0) AS jumlah_pengusul,
    COALESCE(sp.suara_pengusul, 0) AS suara_fase1,
    COALESCE(spm.suara_pemilih, 0) AS suara_fase2,
    (COALESCE(sp.suara_pengusul, 0) + COALESCE(spm.suara_pemilih, 0)) AS total_suara_kandidat,
    COALESCE(tsp.total_suara_masuk, 0) AS total_seluruh_suara,
    COALESCE(rk.rata_skor_kuesioner, 0) AS rata_skor_kuesioner,
    COALESCE(kk.kumpulan_kata, '') AS kata_pengusul
  FROM public.nominee_periode np
  JOIN public.pegawai p ON p.id = np.pegawai_id
  LEFT JOIN public.wilayah w ON w.id = p.wilayah_id
  LEFT JOIN suara_pengusul_cte sp ON sp.periode_id = np.periode_id AND sp.kandidat_id = np.pegawai_id
  LEFT JOIN suara_pemilih_cte spm ON spm.periode_id = np.periode_id AND spm.kandidat_id = np.pegawai_id
  LEFT JOIN rerata_kuesioner_cte rk ON rk.periode_id = np.periode_id AND rk.kandidat_id = np.pegawai_id
  LEFT JOIN kata_kunci_cte kk ON kk.periode_id = np.periode_id AND kk.kandidat_id = np.pegawai_id
  LEFT JOIN total_suara_periode_cte tsp ON tsp.periode_id = np.periode_id
)
SELECT 
  kg.*,
  ROUND(
    CASE 
      WHEN kg.total_seluruh_suara > 0 THEN (kg.total_suara_kandidat::numeric / kg.total_seluruh_suara::numeric) * 40.0 
      ELSE 0 
    END, 2
  ) AS poin_suara,
  ROUND(kg.nilai_ckp * 0.40, 2) AS poin_ckp,
  ROUND(kg.rata_skor_kuesioner * 0.20, 2) AS poin_kuesioner,
  ROUND(
    (
      CASE 
        WHEN kg.total_seluruh_suara > 0 THEN (kg.total_suara_kandidat::numeric / kg.total_seluruh_suara::numeric) * 40.0 
        ELSE 0 
      END
    ) + (kg.nilai_ckp * 0.40) + (kg.rata_skor_kuesioner * 0.20), 2
  ) AS skor_akhir,
  DENSE_RANK() OVER (
    PARTITION BY kg.periode_id 
    ORDER BY (
      (
        CASE 
          WHEN kg.total_seluruh_suara > 0 THEN (kg.total_suara_kandidat::numeric / kg.total_seluruh_suara::numeric) * 40.0 
          ELSE 0 
        END
      ) + (kg.nilai_ckp * 0.40) + (kg.rata_skor_kuesioner * 0.20)
    ) DESC, kg.total_suara_kandidat DESC
  ) AS peringkat
FROM kandidat_gabungan kg;

ALTER VIEW public.view_tabulasi_mode_pionir OWNER TO postgres;
GRANT ALL ON TABLE public.view_tabulasi_mode_pionir TO anon, authenticated, service_role;

-- =============================================================================
-- 10. RPC FUNCTIONS
-- =============================================================================

-- RPC: Ambil akses token PIONIR
CREATE OR REPLACE FUNCTION public.get_akses_pionir_by_token(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_res JSONB;
  v_pengusul RECORD;
  v_penilai RECORD;
  v_periode RECORD;
  v_is_kandidat BOOLEAN := FALSE;
  v_fase INTEGER := 1;
BEGIN
  -- 1. Cek tabel pengusul_periode
  SELECT pp.*, p.nama, p.nip, p.nip_baru, p.jabatan, p.foto_url
  INTO v_pengusul
  FROM public.pengusul_periode pp
  JOIN public.pegawai p ON p.id = pp.pegawai_id
  WHERE pp.token_akses = p_token;

  IF FOUND THEN
    SELECT * INTO v_periode 
    FROM public.periode_penilaian 
    WHERE id = v_pengusul.periode_id;

    IF v_periode.tgl_selesai_fase1 IS NOT NULL AND NOW() > v_periode.tgl_selesai_fase1 THEN
      v_fase := 2;
    ELSE
      v_fase := 1;
    END IF;

    v_res := jsonb_build_object(
      'is_valid', true,
      'peran', 'PENGUSUL',
      'fase', v_fase,
      'is_digunakan', COALESCE(v_pengusul.is_digunakan, false),
      'periode', row_to_json(v_periode),
      'profil', jsonb_build_object(
        'id', v_pengusul.pegawai_id,
        'nama', v_pengusul.nama,
        'nip', v_pengusul.nip,
        'nip_baru', v_pengusul.nip_baru,
        'jabatan', v_pengusul.jabatan,
        'foto_url', v_pengusul.foto_url
      )
    );
    RETURN v_res;
  END IF;

  -- 2. Cek tabel akses_penilai (Pemilih Umum)
  SELECT ap.*, p.nama, p.nip, p.nip_baru, p.jabatan, p.foto_url
  INTO v_penilai
  FROM public.akses_penilai ap
  JOIN public.pegawai p ON p.id = ap.pegawai_id
  WHERE ap.token_akses = p_token;

  IF FOUND THEN
    SELECT * INTO v_periode 
    FROM public.periode_penilaian 
    WHERE id = v_penilai.periode_id;

    -- Cek apakah pemilih ini dicalonkan sebagai kandidat
    SELECT EXISTS (
      SELECT 1 FROM public.nominee_periode 
      WHERE periode_id = v_penilai.periode_id AND pegawai_id = v_penilai.pegawai_id
    ) INTO v_is_kandidat;

    IF v_periode.tgl_selesai_fase1 IS NOT NULL AND NOW() > v_periode.tgl_selesai_fase1 THEN
      v_fase := 2;
    ELSE
      v_fase := 1;
    END IF;

    v_res := jsonb_build_object(
      'is_valid', true,
      'peran', CASE WHEN v_is_kandidat THEN 'KANDIDAT' ELSE 'PEMILIH' END,
      'is_kandidat', v_is_kandidat,
      'fase', v_fase,
      'is_digunakan', COALESCE(v_penilai.is_digunakan, false),
      'periode', row_to_json(v_periode),
      'profil', jsonb_build_object(
        'id', v_penilai.pegawai_id,
        'nama', v_penilai.nama,
        'nip', v_penilai.nip,
        'nip_baru', v_penilai.nip_baru,
        'jabatan', v_penilai.jabatan,
        'foto_url', v_penilai.foto_url
      )
    );
    RETURN v_res;
  END IF;

  RETURN jsonb_build_object('is_valid', false, 'error', 'Token tidak valid');
END;
$$;

-- RPC: Submit Usulan Pengusul (Fase 1)
CREATE OR REPLACE FUNCTION public.submit_usulan_pionir(
  p_token UUID,
  p_kandidat_id BIGINT,
  p_scores_json JSONB,
  p_kata_kunci TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_pengusul RECORD;
  v_periode RECORD;
  v_item JSONB;
  v_q_id BIGINT;
  v_skor NUMERIC;
BEGIN
  SELECT * INTO v_pengusul 
  FROM public.pengusul_periode 
  WHERE token_akses = p_token;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Token pengusul tidak valid.';
  END IF;

  IF v_pengusul.is_digunakan THEN
    RAISE EXCEPTION 'Anda sudah pernah mengirimkan usulan pada periode ini.';
  END IF;

  SELECT * INTO v_periode 
  FROM public.periode_penilaian 
  WHERE id = v_pengusul.periode_id;

  IF v_periode.status != 'BERJALAN' THEN
    RAISE EXCEPTION 'Periode pemilihan tidak aktif.';
  END IF;

  -- Anti self-nomination
  IF v_pengusul.pegawai_id = p_kandidat_id THEN
    RAISE EXCEPTION 'Pengusul tidak diperbolehkan mencalonkan diri sendiri.';
  END IF;

  -- Pengusul lain tidak boleh dicalonkan
  IF EXISTS (
    SELECT 1 FROM public.pengusul_periode 
    WHERE periode_id = v_pengusul.periode_id AND pegawai_id = p_kandidat_id
  ) THEN
    RAISE EXCEPTION 'Pegawai yang bertindak sebagai Pengusul tidak dapat dicalonkan.';
  END IF;

  -- Pengusul dan kandidat harus berasal dari kantor/wilayah kerja yang sama
  IF (SELECT wilayah_id FROM public.pegawai WHERE id = v_pengusul.pegawai_id) IS NOT NULL AND
     (SELECT wilayah_id FROM public.pegawai WHERE id = p_kandidat_id) IS NOT NULL AND
     (SELECT wilayah_id FROM public.pegawai WHERE id = v_pengusul.pegawai_id) <>
     (SELECT wilayah_id FROM public.pegawai WHERE id = p_kandidat_id) THEN
    RAISE EXCEPTION 'Kandidat harus berasal dari kantor/wilayah yang sama dengan Pengusul.';
  END IF;

  -- 1. Insert ke nominee_periode jika belum ada
  INSERT INTO public.nominee_periode (periode_id, pegawai_id, created_at)
  VALUES (v_pengusul.periode_id, p_kandidat_id, NOW())
  ON CONFLICT DO NOTHING;

  -- 2. Insert skor kuesioner per pertanyaan
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_scores_json)
  LOOP
    v_q_id := (v_item->>'pertanyaan_id')::BIGINT;
    v_skor := (v_item->>'skor')::NUMERIC;

    INSERT INTO public.penilaian_pionir_pengusul (
      periode_id,
      pengusul_id,
      kandidat_id,
      pertanyaan_id,
      skor,
      kata_kunci,
      created_at
    ) VALUES (
      v_pengusul.periode_id,
      v_pengusul.pegawai_id,
      p_kandidat_id,
      v_q_id,
      v_skor,
      TRIM(p_kata_kunci),
      NOW()
    )
    ON CONFLICT (periode_id, pengusul_id, kandidat_id, pertanyaan_id)
    DO UPDATE SET 
      skor = EXCLUDED.skor,
      kata_kunci = EXCLUDED.kata_kunci;
  END LOOP;

  -- 3. Tandai token terpakai
  UPDATE public.pengusul_periode
  SET is_digunakan = TRUE,
      submitted_at = NOW()
  WHERE id = v_pengusul.id;

  RETURN jsonb_build_object('success', true, 'message', 'Usulan dan penilaian berhasil dikirim.');
END;
$$;

-- RPC: Submit Vote Pemilih Biasa (Fase 2 - Mode Rahasia LUBER)
CREATE OR REPLACE FUNCTION public.submit_vote_pionir(
  p_token UUID,
  p_kandidat_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_penilai RECORD;
  v_periode RECORD;
  v_hash TEXT;
BEGIN
  SELECT * INTO v_penilai 
  FROM public.akses_penilai 
  WHERE token_akses = p_token;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Token pemilih tidak valid.';
  END IF;

  IF v_penilai.is_digunakan THEN
    RAISE EXCEPTION 'Anda sudah menggunakan hak suara Anda.';
  END IF;

  -- Kandidat dilarang vote
  IF EXISTS (
    SELECT 1 FROM public.nominee_periode 
    WHERE periode_id = v_penilai.periode_id AND pegawai_id = v_penilai.pegawai_id
  ) THEN
    RAISE EXCEPTION 'Kandidat tidak memiliki hak suara dalam pemilihan.';
  END IF;

  SELECT * INTO v_periode 
  FROM public.periode_penilaian 
  WHERE id = v_penilai.periode_id;

  IF v_periode.status != 'BERJALAN' THEN
    RAISE EXCEPTION 'Periode pemilihan tidak aktif.';
  END IF;

  IF v_periode.tgl_selesai_fase1 IS NOT NULL AND NOW() <= v_periode.tgl_selesai_fase1 THEN
    RAISE EXCEPTION 'Tahap voting umum belum dibuka. Mohon tunggu hingga fase pengusulan selesai.';
  END IF;

  v_hash := md5(p_token::text || NOW()::text);

  INSERT INTO public.suara_pionir (
    periode_id,
    kandidat_id,
    voter_hash,
    created_at
  ) VALUES (
    v_penilai.periode_id,
    p_kandidat_id,
    v_hash,
    NOW()
  );

  UPDATE public.akses_penilai
  SET is_digunakan = TRUE,
      submitted_at = NOW()
  WHERE id = v_penilai.id;

  RETURN jsonb_build_object('success', true, 'message', 'Suara Anda berhasil tercatat secara rahasia.');
END;
$$;

-- RPC: Ambil Daftar Kandidat Resmi Mode PIONIR beserta Testimoni Pengusul
CREATE OR REPLACE FUNCTION public.get_kandidat_pionir_periode(p_periode_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_res JSONB;
BEGIN
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', p.id,
      'nama', p.nama,
      'nip', p.nip,
      'nip_baru', p.nip_baru,
      'jabatan', p.jabatan,
      'foto_url', p.foto_url,
      'unit_kerja', w.nama_wilayah,
      'jumlah_pengusul', COALESCE(sub.jml_pengusul, 0),
      'kata_pengusul', COALESCE(sub.kumpulan_kata, '')
    )
  ) INTO v_res
  FROM public.nominee_periode np
  JOIN public.pegawai p ON p.id = np.pegawai_id
  LEFT JOIN public.wilayah w ON w.id = p.wilayah_id
  LEFT JOIN (
    SELECT 
      kandidat_id,
      COUNT(DISTINCT pengusul_id) AS jml_pengusul,
      STRING_AGG(DISTINCT TRIM(kata_kunci), ', ') FILTER (WHERE kata_kunci IS NOT NULL AND TRIM(kata_kunci) != '') AS kumpulan_kata
    FROM public.penilaian_pionir_pengusul
    WHERE periode_id = p_periode_id
    GROUP BY kandidat_id
  ) sub ON sub.kandidat_id = p.id
  WHERE np.periode_id = p_periode_id;

  RETURN COALESCE(v_res, '[]'::jsonb);
END;
$$;

-- RPC: Update Nilai CKP Kandidat oleh Admin
CREATE OR REPLACE FUNCTION public.update_ckp_kandidat_pionir(
  p_periode_id BIGINT,
  p_nominee_id BIGINT,
  p_nilai_ckp NUMERIC
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.nominee_periode
  SET nilai_ckp = p_nilai_ckp
  WHERE periode_id = p_periode_id AND pegawai_id = p_nominee_id;
END;
$$;

-- RPC: Simpan Tim Pengusul oleh Admin (Security Definer)
CREATE OR REPLACE FUNCTION public.simpan_pengusul_pionir(
  p_periode_id BIGINT,
  p_pegawai_ids BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.pengusul_periode (periode_id, pegawai_id)
  SELECT p_periode_id, unnest(p_pegawai_ids)
  ON CONFLICT (periode_id, pegawai_id) DO NOTHING;
END;
$$;

GRANT EXECUTE ON FUNCTION public.simpan_pengusul_pionir(BIGINT, BIGINT[]) TO anon, authenticated, service_role;

